export { default as apiSlice } from './api'
export * from './mockApis/compartment.service.mocktest'
export * from './mockApis/product.service.mocktest'
export * from './compartment.service'
export * from './product.service'
export * from './user.service'